(async()=>{
const pending=[],checks={},tick=()=>new Promise(resolve=>setTimeout(resolve,0));
window.fetch=(path,options)=>new Promise(resolve=>pending.push({path,options,resolve}));
const take=path=>{const i=pending.findIndex(q=>q.path===path);if(i<0)throw Error('Missing synthetic request '+path);return pending.splice(i,1)[0];};
const takeLast=path=>{const i=pending.findLastIndex(q=>q.path===path);if(i<0)throw Error('Missing latest synthetic request '+path);return pending.splice(i,1)[0];};
const response=(q,data,status=200)=>q.resolve({ok:status<400,status,json:async()=>data});
const path=id=>'/api/preparations/'+id+'/local-case';
const detail=(id,revision=1,cycle=1,role='enterprise_operator',state='READY')=>({scope:'SYNTHETIC_LOCAL_CASE_RECORD_ONLY',role,preparation_id:id,case_id:'C-'+id,goal:'SYNTHETIC '+id,case_state:'WAITING_CONFIRMATION',local_record_state:state,revision,cycle,current_snapshot_sha256:role==='enterprise_operator'?'a'.repeat(64):null,verified_snapshot_sha256:state==='REOPENED'?null:'a'.repeat(64),checks:role==='enterprise_operator'?{MATERIAL_REVIEW:[],ACCEPTANCE_RECHECK:[],RECEIPT_RECHECK:[],RESOURCE_RECHECK:[]}:null,required_rechecks:state==='REOPENED'?['MATERIAL_REVIEW','ACCEPTANCE_RECHECK','RECEIPT_RECHECK','RESOURCE_RECHECK']:[],can_revalidate:role==='enterprise_operator'&&state==='REOPENED',can_close_local_record:role==='enterprise_operator'&&state==='READY',can_reopen:role==='enterprise_operator'&&state==='LOCAL_RECORD_CLOSED',history:[],event:null});
const token=t=>{$('token').value=t;$('token').dispatchEvent(new Event('input'));};
const load=id=>loadLocalCase(id).catch(localCaseError);
const ready=async(id,revision=1,cycle=1,role='enterprise_operator',state='READY')=>{const p=load(id);response(takeLast(path(id)),detail(id,revision,cycle,role,state));await p;};
const fill=t=>{$('local-case-reason').value=t;};const send=()=>localCaseCommand('CLOSE_LOCAL_RECORD').catch(localCaseError);
token('synthetic-owner');await ready('A');fill('A reason');await ready('B');checks.cross_case_draft_cleared=$('local-case-reason').value==='';
const late=load('A');await ready('B');fill('safe B');response(take(path('A')),detail('A'));await late;checks.late_read_preserves_case=localCaseId==='B'&&$('local-case-reason').value==='safe B';
let write=send();await tick();let q=take(path('B')+'/commands');const body=q.options.body,key=q.options.headers['Idempotency-Key'];checks.frozen_revision_cycle_sha_reason=JSON.parse(body).expected_revision===1&&JSON.parse(body).expected_cycle===1&&JSON.parse(body).expected_snapshot_sha256==='a'.repeat(64)&&JSON.parse(body).reason==='safe B';response(q,{},409);await write;checks.same_draft_error_preserved=$('local-case-reason').value==='safe B'&&$('local-case-error').textContent.length>0;
write=send();await tick();q=take(path('B')+'/commands');checks.same_input_retry_frozen=q.options.body===body&&q.options.headers['Idempotency-Key']===key;response(q,{event:{revision:2}});await tick();response(take(path('B')),detail('B',2,1,'enterprise_operator','LOCAL_RECORD_CLOSED'));await write;checks.success_clears_unchanged_draft=$('local-case-reason').value==='';
await ready('A');fill('submitted');write=send();await tick();q=take(path('A')+'/commands');fill('edited');$('local-case-error').textContent='';$('page-feedback').textContent='';response(q,{},409);await write;checks.late_error_does_not_pollute_edit=$('local-case-reason').value==='edited'&&$('local-case-error').textContent===''&&$('page-feedback').textContent==='';
await ready('A');fill('submitted');write=send();await tick();q=take(path('A')+'/commands');fill('successful edit');response(q,{event:{revision:2}});await tick();response(take(path('A')),detail('A',2,1,'enterprise_operator','LOCAL_RECORD_CLOSED'));await write;checks.success_preserves_pending_edit=$('local-case-reason').value==='successful edit';
await ready('A');fill('A sent');write=send();await tick();q=take(path('A')+'/commands');await ready('B');fill('B safe');response(q,{event:{revision:2}});await write;checks.late_write_no_followup=localCaseId==='B'&&$('local-case-reason').value==='B safe'&&!pending.length;
const forbidden=load('A');await ready('B');fill('B safe');response(take(path('A')),{},403);await forbidden;checks.stale_forbidden_ignored=localCaseId==='B'&&$('local-case-reason').value==='B safe';
await ready('A');fill('first');write=send();await tick();q=take(path('A')+'/commands');fill('edit');response(q,{},403);await write;checks.current_forbidden_clears_edited_draft=localCaseView===null&&$('local-case-detail').hidden&&$('local-case-reason').value===''&&$('page-feedback').textContent.length>0;
const identity=load('A');token('another owner');response(take(path('A')),detail('A'));await identity;checks.identity_late_read_cleared=localCaseView===null&&$('local-case-history').textContent==='';
await ready('A');const aba=load('A');await ready('B');await ready('A',3,2,'enterprise_operator','REOPENED');fill('new cycle A');response(take(path('A')),detail('A'));await aba;checks.old_cycle_does_not_restore=localCaseView.cycle===2&&localCaseView.revision===3&&$('local-case-reason').value==='new cycle A'&&$('local-case-close').disabled;
await ready('A',3,2,'enterprise_operator','REOPENED');checks.same_case_refresh_preserves_draft=$('local-case-reason').value==='new cycle A';
for(const [name,mutate] of [['preparation_id',()=>localCaseView.preparation_id='OTHER'],['revision',()=>localCaseView.revision=10],['cycle',()=>localCaseView.cycle=10],['sha',()=>localCaseView.current_snapshot_sha256='b'.repeat(64)]]){await ready('A');fill('reason');mutate();let caught=false;try{await localCaseCommand('CLOSE_LOCAL_RECORD');}catch(e){caught=true;}checks[name+'_guard']=caught&&!pending.length;}
const navigation=load('A');document.querySelector('[data-tab=resource]').click();response(take(path('A')),detail('A'));await navigation;checks.navigation_clears=localCaseView===null&&$('local-case-detail').hidden;
await ready('A');const receiptNavigation=loadReceipt('R').catch(receiptError);checks.receipt_selection_clears=localCaseView===null&&$('local-case-detail').hidden;response(take('/api/executor-receipts/R'),{},403);await receiptNavigation;
for(const role of ['park_specialist','service_executor']){await ready('A',2,1,role,'LOCAL_RECORD_CLOSED');checks[role+'_read_only']=$('local-case-decision').hidden&&localCaseView.checks===null&&localCaseView.current_snapshot_sha256===null;}
await ready('A');let x=detail('A',2);x.history=[{cycle:1,revision:2,action:'CLOSE_LOCAL_RECORD',payload:{reason:'<script>globalThis.BAD_CASE=true</script>'}}];renderLocalCase(x);checks.history_script_text_only=!globalThis.BAD_CASE&&!document.querySelector('#local-case-history script')&&$('local-case-history').textContent.includes('<script>');
return JSON.stringify({scope:'CONTROLLED_RESPONSE_ORDER_NOT_BUSINESS_API',checks});
})()
