"""Independent same-purpose material reuse on an owned synthetic API."""
from pathlib import Path
import argparse,json,os,subprocess,sys,time,uuid
from parkweave.process_env import minimal_environment
p=argparse.ArgumentParser();p.add_argument('--report',type=Path,required=True);p.add_argument('--screenshots',type=Path,required=True);p.add_argument('--base-port',type=int,default=8783);a=p.parse_args();context=json.load(sys.stdin);root=Path.cwd()
env=minimal_environment(os.environ,npm_config_cache=str(root/'.cache/npm'),XDG_RUNTIME_DIR=str(root/'.runtime/sockets'))
cached=[x for x in (root/'.cache/npm/_npx').glob('*/node_modules/agent-browser/package.json') if json.loads(x.read_text()).get('version')=='0.38.2'];assert cached
sessions=['pw-mr-'+uuid.uuid4().hex[:10]];active_session=sessions[0]
def browser(*args,stdin=None):
 cmd=['node',str(sorted(cached)[0].parent/'bin/agent-browser.js'),'--session',active_session,'--executable-path','/usr/bin/chromium','--args','--no-sandbox']
 r=subprocess.run(cmd+list(args),input=stdin,capture_output=True,text=True,env=env,timeout=30)
 if r.returncode:raise RuntimeError('cached local material-reuse browser failed: '+r.stderr[:300])
 return r.stdout.strip()
def value(expr):
 r=json.loads(browser('eval','(async()=>JSON.stringify(await ('+expr+')))()'));return json.loads(r) if isinstance(r,str) else r
def wait(expr,pred,timeout=20):
 end=time.monotonic()+timeout
 while time.monotonic()<end:
  x=value(expr)
  if pred(x):return x
  time.sleep(.1)
 raise AssertionError('material-reuse browser timeout '+expr)
def click(selector):
 value('(()=>{window.nativeClicks=0;const b=document.querySelector('+json.dumps(selector)+');b.addEventListener("click",()=>nativeClicks++,{once:true});b.scrollIntoView({block:"center"});return true;})()');browser('snapshot','-i');browser('click',selector);browser('snapshot','-i');assert value('nativeClicks')==1,'native button did not receive click: '+selector
def switch(role):
 browser('eval','--stdin',stdin="document.querySelector('#token').value="+json.dumps(context['tokens'][role])+";document.querySelector('#token').dispatchEvent(new Event('input'));undefined");assert value('preparationView') is None
def track_writes():
 value("(()=>{window.originalFetch=fetch;window.writeRequests=[];window.fetch=(p,o)=>{if(o?.method&&o.method!=='GET')writeRequests.push({path:String(p),action:JSON.parse(o.body||'{}').action||'CREATE'});return originalFetch(p,o);};return true;})()")
def ready():
 wait('materialCorrectionsView',lambda x:isinstance(x,dict) and x['preparation_id']==value('preparationView.preparation.id') and x['preparation_revision']==value('preparationView.preparation.revision'))
 if value('prepRole')=='enterprise_operator':wait('materialReuseView',lambda x:isinstance(x,dict) and x['target']['preparation_id']==value('preparationView.preparation.id') and x['target']['revision']==value('preparationView.preparation.revision') and not value('materialReuseLoading'))
 else:wait('materialReuseView',lambda x:x is None)
 return value('preparationView')
def select(goal):
 click('[data-tab=collaboration]');click('#prep-list');wait("document.querySelector('#prep-items').textContent",lambda x:goal in x);selector=value("'#prep-items button:nth-child('+(Array.from(document.querySelectorAll('#prep-items button')).findIndex(b=>b.textContent.startsWith("+json.dumps(goal)+"))+1)+')'");click(selector);wait('preparationView',lambda x:isinstance(x,dict));return ready()
def draft(slot,text):browser('select','#prep-slot',slot);browser('fill','#prep-text',text);browser('fill','#prep-source-label','SYNTHETIC independent new material source')
def add(slot,text):
 revision=value('preparationView.preparation.revision');draft(slot,text);click('#prep-evidence button');wait('preparationView',lambda x:isinstance(x,dict) and x['preparation']['revision']>revision);return ready()
def decision(selector,reason):
 revision=value('preparationView.preparation.revision');browser('fill','#prep-reason',reason);click(selector);wait('preparationView',lambda x:isinstance(x,dict) and x['preparation']['revision']>revision);return ready()
def capture(name,panel):
 value('(()=>{document.querySelector('+json.dumps(panel)+').scrollIntoView({block:"start"});return true;})()');browser('snapshot','-i');browser('screenshot',str(a.screenshots.resolve()/name))
def reuse_read():
 click('#material-reuse-read');return wait('materialReuseView',lambda x:isinstance(x,dict) and x['target']['preparation_id']==value('preparationView.preparation.id') and x['target']['revision']==value('preparationView.preparation.revision'))
def captures(stage,panel,metrics):
 for width in (1200,390,320):
  browser('set','viewport',str(width),'900' if width==1200 else '844');metric=value('({width:innerWidth,scroll:document.documentElement.scrollWidth})');assert metric['scroll']<=metric['width'];assert 'undefined' not in value('document.querySelector('+json.dumps(panel)+').textContent');metrics.append({'stage':stage,**metric});capture(stage+'-'+str(width)+'.png',panel)
 browser('set','viewport','1200','900')
def commit_lost_reply():
 before=value('preparationView.preparation.revision');browser('check','#material-reuse-purpose');browser('fill','#material-reuse-reason','SYNTHETIC reuse only my material outline for this same service; independently review the new Case')
 value("(()=>{window.savedReuseFetch=fetch;window.reuseAttempts=[];window.dropReuseReply=true;window.fetch=async(p,o)=>{if(String(p).endsWith('/material-reuse')&&o?.method==='POST'){reuseAttempts.push({key:o.headers['Idempotency-Key'],body:o.body});if(dropReuseReply){dropReuseReply=false;const r=await savedReuseFetch(p,o);if(!r.ok)return r;await r.text();throw Error('SYNTHETIC_COMMITTED_REPLY_LOST');}}return savedReuseFetch(p,o);};return true;})()")
 click('#material-reuse-confirm');wait("document.querySelector('#material-reuse-retry').hidden",lambda x:x is False);assert value('reuseAttempts.length')==1 and value('materialReusePending') is not None;assert value("document.querySelector('#prep-evidence button').disabled");click('#material-reuse-retry');wait('preparationView',lambda x:isinstance(x,dict) and x['preparation']['revision']>before);ready();assert value('reuseAttempts.length')==2 and value('reuseAttempts[0].key===reuseAttempts[1].key&&reuseAttempts[0].body===reuseAttempts[1].body');value('(()=>{window.fetch=savedReuseFetch;return true;})()');return reuse_read()
def main():
 a.screenshots.mkdir(parents=True,exist_ok=False);browser('open',f'http://127.0.0.1:{a.base_port}/');browser('snapshot','-i');switch('owner_a');track_writes();source=context['source'];target=context['target'];source_request='SYNTHETIC PRIVATE SOURCE NEED SUMMARY NEVER COPIED';source_outline='SYNTHETIC OWNER ORIGINAL DOCUMENT OUTLINE v1';target_request='SYNTHETIC ENTIRELY NEW TARGET CASE NEED SUMMARY'
 select(source['goal']);add('need_summary',source_request);add('material_outline',source_outline);switch('specialist_a');select(source['goal']);decision('#prep-review','SYNTHETIC independently review original source materials');switch('owner_a');select(source['goal']);decision('#prep-confirm','SYNTHETIC confirm original source local materials');source_view=value('preparationView');source_evidence=next(x for x in source_view['current_materials'] if x['slot']=='material_outline')
 select(target['goal']);assert value('preparationView.current_materials')==[];catalog=reuse_read();assert catalog['can_reuse'] and len(catalog['items'])==1;assert source_request not in json.dumps(catalog) and source_outline not in json.dumps(catalog);assert catalog['items'][0]['source_evidence_id']==source_evidence['id'];browser('select','#material-reuse-source',source_evidence['id']);click('#material-reuse-preview');selected=wait('materialReuseView.source_preview',lambda x:isinstance(x,dict) and x['source_evidence_id']==source_evidence['id']);assert selected['text']==source_outline and source_request not in json.dumps(selected);metrics=[];captures('reuse-selected-purpose','#material-reuse-selected',metrics)
 copied=commit_lost_reply();materials=value('preparationView.current_materials');assert len(materials)==1 and materials[0]['slot']=='material_outline';outline=materials[0];assert outline['id']!=source_evidence['id'] and outline['version']==1 and outline['authenticity']=='UNVERIFIED' and outline['text']==source_outline;assert value('preparationView.preparation.state')=='IN_PREPARATION' and value('preparationView.preparation.review_sha256') is None;assert len(copied['history'])==1;lineage=copied['history'][0]['material_reuse'];assert lineage['requires_independent_review'] and lineage['snapshot_mode']=='INDEPENDENT_COPY';assert source_request not in value("document.querySelector('#prep-materials').textContent");captures('reuse-new-target-unverified','#prep-materials',metrics)
 # A later genuine source revision changes only the source-status projection.
 # The copied target bytes, IDs and lineage remain their immutable snapshot.
 select(source['goal']);decision('#prep-reopen','SYNTHETIC source changed after independent copy');add('material_outline','SYNTHETIC OWNER UPDATED SOURCE OUTLINE v2');select(target['goal']);changed=reuse_read();assert changed['history'][0]['source_status']=='HISTORICAL_SOURCE_CHANGED';assert changed['history'][0]['material_reuse']==lineage;assert value('preparationView.current_materials')[0]==outline
 switch('specialist_a');select(target['goal']);assert value("document.querySelector('#prep-review').disabled");switch('owner_a');select(target['goal']);add('need_summary',target_request);switch('specialist_a');select(target['goal']);assert value("document.querySelector('#material-reuse-read').hidden") or value("document.querySelector('#material-reuse-read').closest('[hidden]')!==null");assert value('materialReuseView') is None;decision('#prep-review','SYNTHETIC new independent target review; historical source approval is not target qualification');switch('owner_a');select(target['goal']);decision('#prep-confirm','SYNTHETIC independently confirm this new target local package');final=reuse_read();assert final['history'][0]['source_status']=='HISTORICAL_SOURCE_CHANGED' and final['history'][0]['material_reuse']==lineage;assert value('preparationView.preparation.state')=='LOCAL_CONFIRMED';current=value('preparationView.current_materials');assert next(x for x in current if x['slot']=='material_outline')==outline;assert next(x for x in current if x['slot']=='need_summary')['text']==target_request;captures('reuse-historical-independent-review','#material-reuse-history',metrics);posts=value('writeRequests')
 browser('reload');browser('snapshot','-i');switch('owner_a');track_writes();select(target['goal']);persisted=reuse_read();assert persisted['history']==final['history'] and value('preparationView.current_materials')==current and value('preparationView.preparation.state')=='LOCAL_CONFIRMED';assert value('writeRequests.length')==0
 # Hold only an actual server GET, then leave its Case or identity before release.
 value(r"(()=>{window.savedLateFetch=fetch;window.releaseReuseRead=null;window.fetch=async(p,o)=>{const r=await savedLateFetch(p,o);if(String(p).endsWith('/material-reuse')&&(!o?.method||o.method==='GET'))await new Promise(resolve=>releaseReuseRead=resolve);return r;};return true;})()");click('#material-reuse-read');wait('typeof releaseReuseRead',lambda x:x=='function');value('(()=>{window.fetch=savedLateFetch;return true;})()');select(source['goal']);value('(()=>{releaseReuseRead();return true;})()');browser('snapshot','-i');wait('materialReuseView',lambda x:isinstance(x,dict) and x['target']['preparation_id']==source['preparation_id']);assert value('preparationView.preparation.id')==source['preparation_id'];assert value('materialReuseView.history')==[] and lineage['reason'] not in value("document.querySelector('#material-reuse-history').textContent")
 select(target['goal']);reuse_read();value(r"(()=>{window.savedLateFetch=fetch;window.releaseReuseRead=null;window.fetch=async(p,o)=>{const r=await savedLateFetch(p,o);if(String(p).endsWith('/material-reuse')&&(!o?.method||o.method==='GET'))await new Promise(resolve=>releaseReuseRead=resolve);return r;};return true;})()");click('#material-reuse-read');wait('typeof releaseReuseRead',lambda x:x=='function');switch('owner_b');value('(()=>{window.fetch=savedLateFetch;releaseReuseRead();return true;})()');browser('snapshot','-i');assert value('materialReuseView') is None and value("document.querySelector('#material-reuse-history').textContent")==''
 denied=value('(async()=>{const r=await fetch("/api/preparations/'+target['preparation_id']+'/material-reuse",{headers:{Authorization:"Bearer "+document.querySelector("#token").value}});return {status:r.status,body:await r.text()};})()');assert denied['status']==403 and source_outline not in denied['body'] and source_request not in denied['body'] and source_evidence['id'] not in denied['body'];switch('specialist_a');denied_specialist=value('(async()=>{const r=await fetch("/api/preparations/'+target['preparation_id']+'/material-reuse",{headers:{Authorization:"Bearer "+document.querySelector("#token").value}});return r.status;})()');assert denied_specialist==403;assert value('writeRequests.length')==0 and not browser('errors')
 a.report.write_text(json.dumps({'scope':'ISOLATED_SAME_OWNER_SAME_SERVICE_INDEPENDENT_MATERIAL_OUTLINE_REUSE','source_preparation_id':source['preparation_id'],'target_preparation_id':target['preparation_id'],'source_case_id':source['case_id'],'target_case_id':target['case_id'],'case_creation_before_browser':True,'source_evidence_id':source_evidence['id'],'target_evidence_id':outline['id'],'material_reuse':lineage,'business_posts':posts,'metadata_catalog_no_material_text':True,'selected_preview_only_explicit_outline':True,'new_independent_unverified_outline_version_one':True,'source_need_summary_never_copied':True,'explicit_same_service_purpose_and_reason':True,'committed_reuse_lost_reply_exact_body_key_recovered':True,'fresh_target_need_summary_and_new_human_review_required':True,'target_review_disabled_until_new_need_summary':True,'source_later_change_preserves_immutable_target_snapshot':True,'history_source_status':'HISTORICAL_SOURCE_CHANGED','reload_new_target_material_and_history_persisted':True,'late_case_read_ignored':True,'late_token_read_ignored':True,'other_owner_status':denied['status'],'specialist_reuse_status':denied_specialist,'viewport_checks':metrics,'case_goal_completed':False,'qualification':'NOT_EVALUATED','external_acceptance':'NOT_SUBMITTED','offline_fulfillment':'NO_EVIDENCE','model_calls':0,'budget':0},ensure_ascii=False,indent=2)+'\n')
try:main()
finally:
 for session in sessions:
  active_session=session;browser('close')
