(async()=>{
const pending=[],checks={};
const tick=()=>new Promise(r=>setTimeout(r,0));
window.fetch=(path,options)=>new Promise(resolve=>pending.push({path,options,resolve}));
const take=path=>{const i=pending.findIndex(q=>q.path===path);if(i<0)throw Error('missing synthetic request '+path);return pending.splice(i,1)[0];};
const answer=(q,x,status=200)=>q.resolve({ok:status<400,status,json:async()=>x});
const switchToken=token=>{$('token').value=token;$('token').dispatchEvent(new Event('input'));};
const meta=id=>({id,name:'SYNTHETIC '+id,capacity:2,revision:1,buffer_seconds:300,enabled:true,open_from:'2030-01-01T00:00:00Z',open_until:'2030-02-01T00:00:00Z',source:{kind:'SYNTHETIC',statement:'test only'}});
const catalog=async()=>{const p=$('resource-catalog').onclick();answer(take('/api/synthetic-resources'),{items:[meta('A'),meta('B')],server_time:'2030-01-01T00:00:00Z'});await p;$('resource-purpose').value='SYNTHETIC purpose';};
const select=id=>{$('resource-select').value=id;$('resource-select').dispatchEvent(new Event('input'));};
const view=(id,available=true)=>({resource_id:id,resource_revision:1,...resourceWindow(),available,occupied_peak:available?0:2,available_quantity:available?2:0,capacity:2,server_time:'2030-01-01T00:00:00Z'});
const preview=async()=>{const p=$('resource-preview').onclick();answer(take('/api/synthetic-resources/'+$('resource-select').value+'/preview'),view($('resource-select').value));await p;};
const hold=(id='hold-A',resource='A',state='HELD')=>({id,resource_id:resource,resource_revision:1,...resourceWindow(),purpose:'SYNTHETIC <script>globalThis.BAD_RESOURCE=true</script>',state,expires_at:'2030-01-01T00:05:00Z'});
const submit=()=>$('resource-form').onsubmit({preventDefault(){}});
switchToken('enterprise-A');const oldCatalog=$('resource-catalog').onclick();const old=take('/api/synthetic-resources');switchToken('enterprise-B');answer(old,{items:[meta('A')],server_time:'2030-01-01T00:00:00Z'});await oldCatalog;
checks.old_identity_catalog_ignored=$('resource-form').hidden&&$('resource-catalog-view').textContent==='';
await catalog();const oldPreview=$('resource-preview').onclick();const q=take('/api/synthetic-resources/A/preview');select('B');answer(q,view('A'));await oldPreview;
checks.old_resource_preview_ignored=resourcePreview===null&&$('resource-hold').disabled;
select('A');const lateWindow=$('resource-preview').onclick();const windowQ=take('/api/synthetic-resources/A/preview');$('resource-start').value='2030-01-01T04:00';answer(windowQ,view('A'));await lateWindow;
checks.programmatic_window_change_ignored=resourcePreview===null&&$('resource-hold').disabled;
await catalog();const first=$('resource-preview').onclick();const firstQ=take('/api/synthetic-resources/A/preview');const second=$('resource-preview').onclick();const secondQ=take('/api/synthetic-resources/A/preview');answer(secondQ,view('A',false));await second;answer(firstQ,view('A',true));await first;
checks.latest_preview_wins=resourcePreview.view.available===false&&$('resource-hold').disabled;
await catalog();await preview();const create=submit();const createQ=take('/api/synthetic-resources/A/holds');const captured=JSON.parse(createQ.options.body);select('B');$('resource-purpose').value='B new purpose';answer(createQ,{hold:hold()});await create;
checks.write_target_captured=createQ.path==='/api/synthetic-resources/A/holds'&&captured.purpose==='SYNTHETIC purpose';
checks.late_write_keeps_new_selection=$('resource-select').value==='B'&&$('resource-purpose').value==='B new purpose'&&$('resource-current').textContent==='';
await catalog();await preview();const identityWrite=submit();const identityQ=take('/api/synthetic-resources/A/holds');switchToken('enterprise-B');answer(identityQ,{hold:hold()});await identityWrite;
checks.old_identity_write_ignored=$('resource-current').textContent===''&&$('resource-form').hidden;
await catalog();const mine=$('resource-mine').onclick();const mineQ=take('/api/resource-holds');await preview();const newWrite=submit();const newQ=take('/api/synthetic-resources/A/holds');answer(newQ,{hold:hold('new-hold')});await newWrite;answer(mineQ,{items:[],has_older_records:false});await mine;
checks.late_list_cannot_clear_new_hold=document.querySelector('#resource-current article').dataset.holdId==='new-hold';
checks.script_purpose_is_text=!globalThis.BAD_RESOURCE&&!$('resource-current').querySelector('script');
const own=$('resource-mine').onclick();answer(take('/api/resource-holds'),{items:[hold()],has_older_records:false});await own;
const releasing=document.querySelector('#resource-hold-items button').onclick();const releasingQ=take('/api/resource-holds/hold-A/release');document.querySelector('[data-tab=service]').click();answer(releasingQ,{hold:hold('hold-A','A','RELEASED')});await releasing;
checks.navigation_ignores_late_release=$('resource-hold-items').textContent===''&&$('resource-form').hidden;
await catalog();await preview();const failing=submit();const failingQ=take('/api/synthetic-resources/A/holds');answer(failingQ,{},409);await failing;
checks.current_failure_keeps_draft=$('resource-purpose').value==='SYNTHETIC purpose'&&$('resource-error').textContent!=='';
checks.conflict_invalidates_preview=resourcePreview===null&&$('resource-hold').disabled;
await catalog();await preview();const unknown=submit();const unknownQ=take('/api/synthetic-resources/A/holds');const key=unknownQ.options.headers['Idempotency-Key'];answer(unknownQ,{},500);await unknown;const retry=submit();const retryQ=take('/api/synthetic-resources/A/holds');checks.ambiguous_retry_same_key=retryQ.options.headers['Idempotency-Key']===key;answer(retryQ,{hold:hold('acknowledged')});await retry;
checks.current_success=document.querySelector('#resource-current article').dataset.holdId==='acknowledged';
await preview();const fresh=submit();const freshQ=take('/api/synthetic-resources/A/holds');checks.new_intent_after_ack_has_new_key=freshQ.options.headers['Idempotency-Key']!==key;answer(freshQ,{hold:hold('fresh-hold')});await fresh;
await catalog();const staleFail=$('resource-preview').onclick();const staleQ=take('/api/synthetic-resources/A/preview');select('B');await preview();answer(staleQ,{},403);await staleFail;
checks.old_forbidden_does_not_clear_new_preview=resourcePreview.view.resource_id==='B'&&$('resource-error').textContent==='';
const repeated1=$('resource-mine').onclick();const list1=take('/api/resource-holds');const repeated2=$('resource-mine').onclick();const list2=take('/api/resource-holds');answer(list2,{items:[hold('current-list','B','EXPIRED')],has_older_records:false});await repeated2;answer(list1,{items:[],has_older_records:false});await repeated1;
checks.latest_own_list_wins=document.querySelector('#resource-hold-items article').dataset.holdId==='current-list';

await catalog();const ownConfirm=$('resource-mine').onclick();answer(take('/api/resource-holds'),{items:[hold('confirm-target')],has_older_records:false});await ownConfirm;
const confirming=document.querySelector('#resource-hold-items [data-resource-action=confirm]').onclick();const confirmQ=take('/api/resource-holds/confirm-target/confirm');
checks.confirm_frozen_revision=JSON.parse(confirmQ.options.body).expected_revision===1;
select('B');$('resource-purpose').value='new B draft';answer(confirmQ,{hold:hold('confirm-target','A','CONFIRMED')});await confirming;
checks.late_confirm_preserves_new_draft=$('resource-select').value==='B'&&$('resource-purpose').value==='new B draft'&&!$('resource-hold-items').textContent.includes('本地合成确认');
await catalog();const currentConfirm=$('resource-mine').onclick();answer(take('/api/resource-holds'),{items:[hold('current-confirm')],has_older_records:false});await currentConfirm;
const firstConfirm=document.querySelector('#resource-hold-items [data-resource-action=confirm]').onclick();const confirmFirstQ=take('/api/resource-holds/current-confirm/confirm');const confirmKey=confirmFirstQ.options.headers['Idempotency-Key'];answer(confirmFirstQ,{},500);await firstConfirm;
const retryConfirm=document.querySelector('#resource-hold-items [data-resource-action=confirm]').onclick();const confirmRetryQ=take('/api/resource-holds/current-confirm/confirm');checks.ambiguous_confirm_retry_same_key=confirmRetryQ.options.headers['Idempotency-Key']===confirmKey;
answer(confirmRetryQ,{hold:hold('current-confirm','A','CONFIRMED')});await retryConfirm;
checks.confirmed_has_cancel_no_confirm=!!document.querySelector('#resource-hold-items [data-resource-action=release]')&&!document.querySelector('#resource-hold-items [data-resource-action=confirm]')&&$('resource-hold-items').textContent.includes('本地合成确认');

await catalog();const cancelledReplayList=$('resource-mine').onclick();answer(take('/api/resource-holds'),{items:[hold('cancelled-replay')],has_older_records:false});await cancelledReplayList;
const lostConfirm=document.querySelector('#resource-hold-items [data-resource-action=confirm]').onclick();const lostConfirmQ=take('/api/resource-holds/cancelled-replay/confirm');const lostKey=lostConfirmQ.options.headers['Idempotency-Key'];answer(lostConfirmQ,{},500);await lostConfirm;
const cancelledReplay=document.querySelector('#resource-hold-items [data-resource-action=confirm]').onclick();const cancelledReplayQ=take('/api/resource-holds/cancelled-replay/confirm');checks.cancelled_confirm_retry_same_key=cancelledReplayQ.options.headers['Idempotency-Key']===lostKey;
answer(cancelledReplayQ,{hold:hold('cancelled-replay','A','RELEASED'),receipt:{action:'CONFIRM',observed_state:'CONFIRMED'}});await cancelledReplay;
checks.cancelled_confirm_replay_uses_current_state=$('resource-hold-items').textContent.includes('占位已释放')&&$('resource-preview-result').textContent.includes('已释放')&&!$('resource-preview-result').textContent.includes('已核对本地合成确认');
return JSON.stringify({checks,scope:'SYNTHETIC_RESOURCE_UI_RESPONSE_ORDER_ONLY'});
})()
