(async()=>{
const pending=[],checks={},tick=()=>new Promise(resolve=>setTimeout(resolve,0));
window.fetch=(path,options)=>new Promise(resolve=>pending.push({path,options,resolve}));
const take=path=>{const i=pending.findIndex(q=>q.path===path);if(i<0)throw Error('Missing synthetic request '+path);return pending.splice(i,1)[0];};
const takeLast=path=>{const i=pending.findLastIndex(q=>q.path===path);if(i<0)throw Error('Missing latest synthetic request '+path);return pending.splice(i,1)[0];};
const response=(q,data,status=200)=>q.resolve({ok:status<400,status,json:async()=>data});
const path=id=>'/api/preparations/'+id+'/dispatch';
const detail=(id,revision=1,role='service_executor',state='OFFERED')=>({scope:'SYNTHETIC_INTERNAL_DISPATCH_ONLY',role,preparation_id:id,goal:'SYNTHETIC '+id,service_id:'synthetic-material-preparation',service_version:1,preparation_revision:5,dispatch_id:'D-'+id,revision,current_offer:{id:'O-'+id,executor_id:'synthetic-executor',state,reason:'SYNTHETIC offer'},offers:[],history:[],event:null,dependency:'CURRENT',receipt_step_id:null,is_current_offer:true});
const switchToken=token=>{$('token').value=token;$('token').dispatchEvent(new Event('input'));};
const load=id=>loadDispatch(id).catch(dispatchError);
const ready=async(id,revision=1,role='service_executor',state='OFFERED')=>{const p=load(id);response(takeLast(path(id)),detail(id,revision,role,state));if(role==='park_specialist'){await tick();response(take('/api/service-dispatches/catalog?preparation_id='+id),{preparation_revision:5,dispatch_revision:revision,ready:state==='WITHDRAWN',executors:[{id:'E-1'},{id:'E-2'}],has_receipt_step:false});}await p;};
const fill=t=>{$('dispatch-decision-reason').value=t;};
switchToken('synthetic-executor');await ready('A');fill('A reason');await ready('B');checks.cross_case_drafts_cleared=$('dispatch-decision-reason').value===''&&$('dispatch-offer-reason').value==='';
const late=load('A');await ready('B');fill('safe B');response(take(path('A')),detail('A'));await late;checks.late_read_preserves_selected_case=dispatchPreparationId==='B'&&$('dispatch-decision-reason').value==='safe B';
const send=()=>dispatchWrite('ACCEPT').catch(dispatchError);
let write=send();await tick();let q=take('/api/service-dispatches/D-B/commands');checks.write_revision_and_reason_snapshot=JSON.parse(q.options.body).expected_revision===1&&JSON.parse(q.options.body).reason==='safe B';
const key=q.options.headers['Idempotency-Key'],body=q.options.body;response(q,{},409);await write;checks.same_draft_failure_preserved=$('dispatch-decision-reason').value==='safe B'&&$('dispatch-error').textContent.length>0;
write=send();await tick();q=take('/api/service-dispatches/D-B/commands');checks.same_input_retry_frozen=q.options.headers['Idempotency-Key']===key&&q.options.body===body;response(q,{dispatch_id:'D-B',event:{revision:2}});await tick();response(take(path('B')),detail('B',2,'service_executor','ACCEPTED'));await write;checks.success_clears_unchanged_draft=$('dispatch-decision-reason').value==='';
await ready('A');fill('submitted');write=send();await tick();q=take('/api/service-dispatches/D-A/commands');fill('new draft');$('dispatch-error').textContent='';$('page-feedback').textContent='';response(q,{},409);await write;checks.late_failure_does_not_pollute_edited_draft=$('dispatch-decision-reason').value==='new draft'&&$('dispatch-error').textContent===''&&$('page-feedback').textContent==='';
await ready('A');fill('submitted');write=send();await tick();q=take('/api/service-dispatches/D-A/commands');fill('new successful edit');response(q,{dispatch_id:'D-A',event:{revision:2}});await tick();response(take(path('A')),detail('A',2,'service_executor','ACCEPTED'));await write;checks.success_preserves_pending_edit=$('dispatch-decision-reason').value==='new successful edit';
await ready('A');fill('A sent');write=send();await tick();q=take('/api/service-dispatches/D-A/commands');await ready('B');fill('B safe');response(q,{dispatch_id:'D-A',event:{revision:2}});await write;checks.late_write_has_no_followup=dispatchPreparationId==='B'&&$('dispatch-decision-reason').value==='B safe'&&!pending.length;
const denied=load('A');await ready('B');fill('B safe');response(take(path('A')),{},403);await denied;checks.stale_forbidden_ignored=dispatchPreparationId==='B'&&$('dispatch-decision-reason').value==='B safe';
await ready('A');fill('first');write=send();await tick();q=take('/api/service-dispatches/D-A/commands');fill('edited');response(q,{},403);await write;checks.current_forbidden_clears_even_edited_draft=dispatchView===null&&$('dispatch-detail').hidden&&$('dispatch-decision-reason').value===''&&$('page-feedback').textContent.length>0;
const readDenied=load('A');response(take(path('A')),{},403);await readDenied;checks.read_forbidden_feedback_visible=$('dispatch-detail').hidden&&$('page-feedback').textContent.length>0;
const identity=load('A');switchToken('new identity');response(take(path('A')),detail('A'));await identity;checks.identity_late_read_cleared=dispatchView===null&&$('dispatch-history').textContent==='';
await ready('A');const aba=load('A');await ready('B');await ready('A',3);fill('new A');response(take(path('A')),detail('A',1));await aba;checks.return_generation_preserves_new_state=dispatchView.revision===3&&$('dispatch-decision-reason').value==='new A';
await ready('A',3);checks.same_case_refresh_preserves_draft=$('dispatch-decision-reason').value==='new A';
for(const [name,mutate] of [['dispatch_id',()=>dispatchView.dispatch_id='OTHER'],['preparation_id',()=>dispatchView.preparation_id='OTHER'],['revision',()=>dispatchView.revision=10],['offer_id',()=>dispatchView.current_offer.id='OTHER']]){await ready('A');fill('reason');mutate();let caught=false;try{await dispatchWrite('ACCEPT');}catch(e){caught=true;}checks[name+'_guard']=caught&&!pending.length;}
const list=$('dispatch-list').onclick();q=take('/api/service-dispatches');switchToken('other');response(q,{items:[{preparation_id:'A',goal:'PRIVATE OLD'}]});await list;checks.late_list_ignored=$('dispatch-items').textContent==='';
const navigation=load('A');document.querySelector('[data-tab=resource]').click();response(take(path('A')),detail('A'));await navigation;checks.navigation_clears_private_dispatch=dispatchView===null&&$('dispatch-detail').hidden;
switchToken('reviewer');let reading=load('A');response(take(path('A')),detail('A',2,'park_specialist','WITHDRAWN'));await tick();q=take('/api/service-dispatches/catalog?preparation_id=A');switchToken('executor');response(q,{preparation_revision:5,dispatch_revision:2,ready:true,executors:[{id:'OLD-TARGET'}]});await reading;checks.late_catalog_ignored=$('dispatch-executor').textContent==='';
switchToken('reviewer');await ready('A',2,'park_specialist','WITHDRAWN');$('dispatch-offer-reason').value='old offer';write=dispatchWrite('OFFER').catch(dispatchError);await tick();q=take(path('A'));$('dispatch-executor').value='E-2';$('dispatch-offer-reason').value='new offer';$('dispatch-error').textContent='';$('page-feedback').textContent='';response(q,{},422);await write;checks.late_offer_failure_does_not_pollute_new_target=$('dispatch-executor').value==='E-2'&&$('dispatch-offer-reason').value==='new offer'&&$('dispatch-error').textContent===''&&$('page-feedback').textContent==='';
return JSON.stringify({scope:'CONTROLLED_RESPONSE_ORDER_NOT_BUSINESS_API',checks});
})()
